season: 202526
current_gw: 3
blacklist:
  names:
  - Mohamed Salah
  - Erling Haaland
  price_min: 13.0
whitelist:
  names: []
prediction:
  mode: baseline
  min_availability: 0.15
  availability_power: 1.0
  base_by_pos:
    GK: 3.4
    DEF: 3.7
    MID: 4.5
    FWD: 4.8
  spread_by_pos:
    GK: 1.1
    DEF: 1.2
    MID: 1.4
    FWD: 1.4
chips:
  thresholds:
    bench_boost_min_bench_ep: 20.0
    triple_captain_min_ep: 9.0
    triple_captain_min_ep_if_double: 7.5
    free_hit_min_active_starters: 9
dgw_adjust:
  alpha_per_extra_match: 0.65
  availability_floor: 0.5
  availability_penalty: 0.8
bench_order:
  weight_availability: 0.5
optimizer:
  squad_builder:
    budget: 100.0
    w_ep: 1.0
    w_avail: 0.3
    w_vpm: 0.1
