# 当前阵容（15 名球员的 player_id）
squad:
  - 253   # GK
  - 502   # GK
  - 402   # DEF
  - 370
  - 5
  - 225
  - 672
  - 119 # MID
  - 417
  - 82
  - 450
  - 413
  - 661 # FWD
  - 681
  - 283

# 银行（单位：£m）
bank: 0

# 免费转会数
free_transfers: 1
