# 当前阵容（15 名球员的 player_id）
squad: []

# 银行（单位：£m）
bank: 0

# 免费转会数
free_transfers: 1

chips_available:
  wildcard: true
  free_hit: true
  bench_boost: true
  triple_captain: true

purchase_prices: {}
