name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: pip install -U uv
      - name: Install project (with dev deps)
        run: uv pip install --system -e ".[dev]"
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Import order (isort)
        run: isort --check-only .
      - name: Type check (mypy)
        run: mypy src
      - name: Tests
        run: pytest -q
